# Generated by Django 5.1.2 on 2024-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0005_user_no_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_plate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
