# Generated by Django 5.1.2 on 2024-10-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_alter_user_no_phone_alter_user_no_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
