# Generated by Django 5.1.2 on 2024-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0007_remove_booking_total_price_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_plate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
