# Generated by Django 5.1.2 on 2024-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0008_booking_no_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_plate',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
