# Generated by Django 5.1.2 on 2024-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0009_alter_user_no_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
