# Generated by Django 5.1.2 on 2024-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0010_booking_no_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
