# Generated by Django 5.1.2 on 2024-10-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0013_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
