# Generated by Django 5.1.2 on 2024-10-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0014_booking_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_status', models.BooleanField(default=False)),
                ('slot_time', models.DateTimeField()),
            ],
        ),
    ]
