# Generated by Django 5.0.2 on 2024-10-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0015_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
