# Generated by Django 5.0.2 on 2024-10-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0016_delete_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_status', models.BooleanField(default=False)),
                ('slot_time', models.TimeField()),
            ],
        ),
    ]
